In [338]:
import cv2
import numpy as np
np.set_printoptions(threshold=np.inf)
from matplotlib import pyplot as plt
from os.path import isfile, join
from os import listdir
from sklearn import preprocessing
from skimage import filters

# TASK 1 - Compute image descriptors (QS1)

### Calcular els histogrames de totes les imatges de la carpeta especificada a "imagesFolder"
Aquí la idea es fer el bucle que recorre totes les imatges i calcula el histograma de cadascuna d'elles, afegint el resultat a una matriu d'histogrames que després ens servirán per calcular les "Similarity measures".
Cada fila correspondrà a una imatge. 

In [339]:
imagesFolder = "./bbdd/"
histogram_bbdd_matrix = np.empty([0, 256*3]) #Creem una matriu buida
print(histogram_bbdd_matrix.shape)
for filename in sorted(listdir(imagesFolder)):
    if(filename != '.DS_Store'):
        print("******************************************************************************")
        print("IMAGE: " + filename)
        print("******************************************************************************")

        img = cv2.imread(imagesFolder + filename)
        img = cv2.cvtColor(img,cv2.COLOR_BGR2Lab)
        
        colorx = ('x','y','z')
        hist_img = np.empty([0,0])
        for i,col in enumerate(colorx):
            hist = cv2.calcHist([img],[i],None,[256],[0,256]) #Calculem histogrames
            hist = preprocessing.normalize(hist, norm='max') #Normalitzem histogrames
            hist_t = hist.transpose()
            print(hist_t.shape)
            if i == 0:
                hist_img = hist_t
            else:
                hist_img = np.concatenate((hist_img, hist_t), axis = 1)
            
        histogram_bbdd_matrix = np.vstack((histogram_bbdd_matrix, hist_img))   

(0, 768)
******************************************************************************
IMAGE: bbdd_00000.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00001.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00002.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00003.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00004.jpg
**************************************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00041.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00042.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00043.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00044.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00045.jpg
********************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00087.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00088.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00089.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00090.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00091.jpg
********************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00131.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00132.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00133.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00134.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00135.jpg
********************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00174.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00175.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00176.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00177.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00178.jpg
********************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00218.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00219.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00220.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00221.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00222.jpg
********************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00258.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00259.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00260.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00261.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00262.jpg
********************************************

In [ ]:
print(histogram_bbdd_matrix.shape)

### Calcular els histogrames de totes les imatges de la carpeta de query (qsd1_w1)

In [ ]:
queryFolder = "./qsd1_w1/"
histogram_query_matrix = np.empty([0, 256*3])
for filename in sorted(listdir(queryFolder)):
    if(filename != '.DS_Store' and (filename.split('.')[1] == 'jpg' or filename.split('.')[1] == 'png')):
        print("******************************************************************************")
        print("./qsd1_w1/" + filename)
        print("******************************************************************************")

        query_img = cv2.imread(queryFolder + filename)
        query_img = cv2.cvtColor(query_img,cv2.COLOR_BGR2Lab)
        color = ('b','g','r')
        hist_query = np.empty([0, 256*3])
        
        for i,col in enumerate(color):
            histr = cv2.calcHist([query_img],[i],None,[256],[0,256])
            histr = preprocessing.normalize(histr, norm='max')
            histr = histr.transpose()
            if i == 0:
                hist_query = histr
            else:
                hist_query = np.concatenate((hist_query,histr), axis = 1)
        
        histogram_query_matrix = np.vstack((histogram_query_matrix, hist_query))
    


In [ ]:
print(histogram_query_matrix.shape)

# TASK 2 - Similarity measures

### Euclidean distance

In [ ]:
from scipy.spatial import distance

dst = np.zeros((30, 279))
matrix_retrieval = np.zeros((30,10))

for query_image_index in range(0,len(histogram_query_matrix)): 
    for bbdd_image_index in range(0, len(histogram_bbdd_matrix)):
        
        #Euclidian distance 1
        dst[query_image_index,bbdd_image_index] = distance.euclidean(histogram_query_matrix[query_image_index,:], histogram_bbdd_matrix[bbdd_image_index,:])
        
        #Euclidian distance 2
        dst[query_image_index,bbdd_image_index] = np.linalg.norm(histogram_query_matrix[query_image_index,:] - histogram_bbdd_matrix[bbdd_image_index,:], ord=1)
        
        #Bray Curtis Distance
        dst[query_image_index,bbdd_image_index] = distance.braycurtis(histogram_query_matrix[query_image_index,:], histogram_bbdd_matrix[bbdd_image_index,:])
    
    matrix_retrieval[query_image_index,:] = np.argsort(dst[query_image_index,:])[:10]

print(matrix_retrieval)

# Task 4

In [ ]:
import ml_metrics as metrics
import pickle

with open('./qsd1_w1/gt_corresps.pkl', 'rb') as fd:
        ll = pickle.load(fd)
        print(ll)

#Convertir idx(numpy) a list of lists
matrix_retrieval_lst = matrix_retrieval.tolist()

#print(matrix_retrieval_lst)

ll_prp = np.zeros((len(ll),1))

for i in range(0,len(ll)):
    ll_prp[i] = ll[i][0][1]

ll_prp_lst = ll_prp.tolist()

mapak = metrics.average_precision.mapk(ll_prp_lst, matrix_retrieval_lst, k=10)        

print(mapak)

# Task 5

In [340]:
query2folder = './qsd2_w1/'

histogram_query2_matrix = np.empty([0, 256*3])
for filename in sorted(listdir(query2folder)):
    count = 0
    if(filename != '.DS_Store' and (filename.split('.')[1] == 'jpg')):
        print("******************************************************************************")
        print("./qsd1_w1/" + filename)
        print("******************************************************************************")

        query_img = cv2.imread(query2folder + filename)
        
        gray = cv2.cvtColor(query_img, cv2.COLOR_BGR2GRAY)

        ret, thresh = cv2.threshold(gray,0,255,cv2.THRESH_BINARY_INV+cv2.THRESH_OTSU)

        # noise removal
        kernel = np.ones((3,3),np.uint8)
        opening = cv2.morphologyEx(thresh,cv2.MORPH_OPEN,kernel, iterations = 2)

        # sure background area
        sure_bg = cv2.dilate(opening,kernel,iterations=3) #Fals. El sure 


        # Finding sure foreground area
        dist_transform = cv2.distanceTransform(opening,cv2.DIST_L2,3)
        ret, sure_fg = cv2.threshold(dist_transform,0.6*dist_transform.max(),255,0)



        # Finding unknown region
        sure_fg = np.uint8(sure_fg)
        unknown = cv2.subtract(sure_bg,sure_fg)

        # Marker labelling
        ret, markers = cv2.connectedComponents(sure_fg)

        markers[markers != 0] = 200

        markers[0:35,:] = 100
        sure_fg[0:35,:] = 100
        markers[len(markers)-36:len(markers)-1,:] = 100
        sure_fg[len(markers)-36:len(markers)-1,:] = 100
        markers[:,0:35] = 100
        sure_fg[:,0:35] = 100
        markers[:,len(markers[0,:])-36:len(markers[0,:])-1] = 100
        sure_fg[:,len(markers[0,:])-36:len(markers[0,:])-1] = 100

        # Add one to all labels so that sure background is not 0, but 1
        markers = markers+1

        # Now, mark the region of unknown with zero
        markers[sure_fg == 0] = 0

        markersres = cv2.watershed(query_img,markers)

        markersres[markersres == 201] = 255
        markersres[markersres == 101] = 0
        markersres[markersres == -1] = 255
        
        #Make the mask binary
        markersres = markersres/np.max(markersres)
        
        #Count the number of black pixels (markersres = 0)
        unique, counts = np.unique(markersres, return_counts=True)
        #print(counts)
        
        #Apply the mask to the image
        color = ('b','g','r')
        for i,col in enumerate(color):#Aquesta part d'aqui no funciona tampoc diria de moment
            query_img[:,:,i] = query_img[:,:,i]*markersres
        
        #Compute the histogram
        query_img = cv2.cvtColor(query_img,cv2.COLOR_BGR2Lab)
        
        hist_query = np.empty([0, 256*3])
        for i,col in enumerate(color):
            histr = cv2.calcHist([query_img],[i],None,[256],[0,256])
            print(histr.shape)
            #Discount the number of black pixels from the corresponding bin on the histogram. 
            histr[0] = histr[0]-counts[0] #-->Fet bastant a lo loco, nidea de si així xuta o no.
            histr = preprocessing.normalize(histr, norm='max')
            histr = histr.transpose()
            if i == 0:
                hist_query = histr
            else:
                hist_query = np.concatenate((hist_query,histr), axis = 1)
        
             
        
        #Save to the histogram_query matrix      
        histogram_query2_matrix = np.vstack((histogram_query2_matrix, hist_query))
        
        


******************************************************************************
./qsd1_w1/00000.jpg
******************************************************************************
(256, 1)
(256, 1)
(256, 1)
******************************************************************************
./qsd1_w1/00001.jpg
******************************************************************************
(256, 1)
(256, 1)
(256, 1)
******************************************************************************
./qsd1_w1/00002.jpg
******************************************************************************
(256, 1)
(256, 1)
(256, 1)
******************************************************************************
./qsd1_w1/00003.jpg
******************************************************************************
(256, 1)
(256, 1)
(256, 1)
******************************************************************************
./qsd1_w1/00004.jpg
******************************************************************************
(2

In [341]:
from scipy.spatial import distance

dst = np.zeros((30, 279))
matrix_retrieval = np.zeros((30,10))

for query_image_index in range(0,len(histogram_query2_matrix)): 
    for bbdd_image_index in range(0, len(histogram_bbdd_matrix)):
        
        #Euclidian distance 1
        dst[query_image_index,bbdd_image_index] = distance.euclidean(histogram_query2_matrix[query_image_index,:], histogram_bbdd_matrix[bbdd_image_index,:])
        
        #Euclidian distance 2
        dst[query_image_index,bbdd_image_index] = np.linalg.norm(histogram_query2_matrix[query_image_index,:] - histogram_bbdd_matrix[bbdd_image_index,:], ord=1)
        
        #Bray Curtis Distance
        dst[query_image_index,bbdd_image_index] = distance.braycurtis(histogram_query2_matrix[query_image_index,:], histogram_bbdd_matrix[bbdd_image_index,:])
    
    matrix_retrieval[query_image_index,:] = np.argsort(dst[query_image_index,:])[:10]

print(matrix_retrieval)

[[137. 191.  26. 109.  20. 257. 164. 115.  59. 134.]
 [130.  62. 106.  53.  33.  85.  54. 275. 178.  96.]
 [143.  69. 220. 197. 117. 216. 126.  18.  94.   9.]
 [129.  42.  22. 120. 168.  57. 214.  78.  51. 170.]
 [ 91.   7.  81. 131.  93. 173. 278.  19. 154. 140.]
 [218. 227.  49.  66. 265. 251. 150. 254. 161. 240.]
 [ 83. 232.  70. 197. 194.   4. 128. 180.  60.  30.]
 [278. 226. 167. 132. 173. 154.   7. 236.  91. 140.]
 [277.  36. 258. 182. 110. 130.  96. 155. 238. 221.]
 [ 70.  31.  30. 177. 176.   4. 157.  89.  60. 128.]
 [ 73. 144. 148. 268. 123. 138.  20.  59. 215.  82.]
 [ 92. 158. 179. 176.  19. 104. 157. 177. 131.  70.]
 [238. 252.  33. 181.  95. 106. 253. 266. 155. 182.]
 [207. 157. 274. 131. 177.  89. 179.  70.  81. 187.]
 [181.  95. 238. 252. 253.  33. 198. 266. 182. 106.]
 [186. 223. 152. 114. 240. 237.  43. 267. 165. 107.]
 [215. 144. 123.  20. 268. 115. 148.  56.  59. 109.]
 [128. 180.  83.  70. 194.  85.   4.  60.  30. 232.]
 [207. 274. 172. 157. 187.  89.   4. 128. 165.

In [343]:
import ml_metrics as metrics
import pickle

with open('./qsd2_w1/gt_corresps.pkl', 'rb') as fd:
        ll = pickle.load(fd)
        print(ll)

#Convertir idx(numpy) a list of lists
matrix_retrieval_lst = matrix_retrieval.tolist()

#print(matrix_retrieval_lst)

ll_prp = np.zeros((len(ll),1))

for i in range(0,len(ll)):
    ll_prp[i] = ll[i][0][1]

ll_prp_lst = ll_prp.tolist()

mapak = metrics.average_precision.mapk(ll_prp_lst, matrix_retrieval_lst, k=10)        

print(mapak)

[[[0, 228]], [[1, 62]], [[2, 0]], [[3, 129]], [[4, 42]], [[5, 218]], [[6, 40]], [[7, 101]], [[8, 279]], [[9, 180]], [[10, 73]], [[11, 127]], [[12, 155]], [[13, 106]], [[14, 193]], [[15, 131]], [[16, 215]], [[17, 257]], [[18, 155]], [[19, 139]], [[20, 171]], [[21, 5]], [[22, 205]], [[23, 14]], [[24, 160]], [[25, 249]], [[26, 147]], [[27, 66]], [[28, 242]], [[29, 6]]]
0.18703703703703703
