In [1]:
import cv2
import numpy as np
np.set_printoptions(threshold=np.inf)
from matplotlib import pyplot as plt
from os.path import isfile, join
from os import listdir
from sklearn import preprocessing
from skimage import filters

# TASK 1

### Calcular els histogrames de totes les imatges de la carpeta especificada a "imagesFolder"
Aquí la idea es fer el bucle que recorre totes les imatges i calcula el histograma de cadascuna d'elles, afegint el resultat a una matriu d'histogrames que després ens servirán per calcular les "Similarity measures".
Cada fila correspondrà a una imatge. 

In [2]:
imagesFolder = "./bbdd/"
histogram_bbdd_matrix = np.empty([0, 256*3]) #Creem una matriu buida
print(histogram_bbdd_matrix.shape)
for filename in sorted(listdir(imagesFolder)):
    if(filename != '.DS_Store'):
        print("******************************************************************************")
        print("IMAGE: " + filename)
        print("******************************************************************************")

        img = cv2.imread(imagesFolder + filename)
        img = cv2.cvtColor(img,cv2.COLOR_BGR2Lab)
        
        colorx = ('x','y','z')
        hist_img = np.empty([0,0])
        for i,col in enumerate(colorx):
            hist = cv2.calcHist([img],[i],None,[256],[0,256]) #Calculem histogrames
            hist_t = hist.transpose()
            print(hist_t.shape)
            if i == 0:
                hist_img = hist_t
            else:
                hist_img = np.concatenate((hist_img, hist_t), axis = 1)
        
        cv2.normalize(hist_img, hist_img, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX)
        histogram_bbdd_matrix = np.vstack((histogram_bbdd_matrix, hist_img))   

(0, 768)
******************************************************************************
IMAGE: bbdd_00000.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00001.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00002.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00003.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00004.jpg
**************************************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00041.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00042.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00043.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00044.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00045.jpg
********************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00088.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00089.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00090.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00091.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00092.jpg
********************************************

(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00131.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00132.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00133.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00134.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00135.jpg
*****************************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00175.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00176.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00177.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00178.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00179.jpg
********************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00218.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00219.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00220.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00221.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00222.jpg
********************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00259.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00260.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00261.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00262.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00263.jpg
********************************************

In [3]:
print(histogram_bbdd_matrix.shape)

(279, 768)


### Calcular els histogrames de totes les imatges de la carpeta de query (qsd1_w1)

In [ ]:
queryFolder = "./qsd1_w1/"
histogram_query_matrix = np.empty([0, 256*3])
for filename in sorted(listdir(queryFolder)):
    if(filename != '.DS_Store' and (filename.split('.')[1] == 'jpg' or filename.split('.')[1] == 'png')):
        print("******************************************************************************")
        print("./qsd1_w1/" + filename)
        print("******************************************************************************")

        query_img = cv2.imread(queryFolder + filename)
        query_img = cv2.cvtColor(query_img,cv2.COLOR_BGR2Lab)
        color = ('b','g','r')
        hist_query = np.empty([0, 256*3])
        
        for i,col in enumerate(color):
            histr = cv2.calcHist([query_img],[i],None,[256],[0,256])
            histr = preprocessing.normalize(histr, norm='max')
            histr = histr.transpose()
            if i == 0:
                hist_query = histr
            else:
                hist_query = np.concatenate((hist_query,histr), axis = 1)
        
        cv2.normalize(hist_query, hist_query, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX)
        histogram_query_matrix = np.vstack((histogram_query_matrix, hist_query))
    


In [ ]:
print(histogram_query_matrix.shape)

# TASK 2 - Similarity measures

### Euclidean distance

In [ ]:
from scipy.spatial import distance

dst = np.zeros((30, 279))
matrix_retrieval = np.zeros((30,10))

for query_image_index in range(0,len(histogram_query_matrix)): 
    for bbdd_image_index in range(0, len(histogram_bbdd_matrix)):
        
        #Euclidian distance 1
        #dst[query_image_index,bbdd_image_index] = distance.euclidean(histogram_query_matrix[query_image_index,:], histogram_bbdd_matrix[bbdd_image_index,:])
        
        #Euclidian distance 2
        dst[query_image_index,bbdd_image_index] = np.linalg.norm(histogram_query_matrix[query_image_index,:] - histogram_bbdd_matrix[bbdd_image_index,:], ord=1)
        
        #Bray Curtis Distance
        #dst[query_image_index,bbdd_image_index] = distance.braycurtis(histogram_query_matrix[query_image_index,:], histogram_bbdd_matrix[bbdd_image_index,:])
    
    matrix_retrieval[query_image_index,:] = np.argsort(dst[query_image_index,:])[:10]

print(matrix_retrieval)

### L1 distance

In [ ]:
from scipy.spatial import distance

dst = np.zeros((30, 279))
matrix_retrieval = np.zeros((30,10))

for query_image_index in range(0,len(histogram_query_matrix)): 
    for bbdd_image_index in range(0, len(histogram_bbdd_matrix)):
        
        #Euclidian distance 1
        dst[query_image_index,bbdd_image_index] = distance.euclidean(histogram_query_matrix[query_image_index,:], histogram_bbdd_matrix[bbdd_image_index,:])
    
    matrix_retrieval[query_image_index,:] = np.argsort(dst[query_image_index,:])[:10]

print(matrix_retrieval)

### X2 distance

In [ ]:
from scipy.spatial import distance

dst = np.zeros((30, 279))
matrix_retrieval = np.zeros((30,10))

for query_image_index in range(0,len(histogram_query_matrix)): 
    for bbdd_image_index in range(0, len(histogram_bbdd_matrix)):
        
        #Euclidian distance 1
        dst[query_image_index,bbdd_image_index] = distance.euclidean(histogram_query_matrix[query_image_index,:], histogram_bbdd_matrix[bbdd_image_index,:])
    
    matrix_retrieval[query_image_index,:] = np.argsort(dst[query_image_index,:])[:10]

print(matrix_retrieval)

# Task 4

In [ ]:
import ml_metrics as metrics
import pickle

with open('./qsd1_w1/gt_corresps.pkl', 'rb') as fd:
        ll = pickle.load(fd)
        print(ll)

#Convertir idx(numpy) a list of lists
matrix_retrieval_lst = matrix_retrieval.tolist()

#print(matrix_retrieval_lst)

ll_prp = np.zeros((len(ll),1))

for i in range(0,len(ll)):
    ll_prp[i] = ll[i][0]

ll_prp_lst = ll_prp.tolist()

mapak = metrics.average_precision.mapk(ll_prp_lst, matrix_retrieval_lst, k=10)        

print(mapak)

# Task 5

In [4]:
query2folder = './qsd2_w1/'

histogram_query2_matrix = np.empty([0, 256*3])
for filename in sorted(listdir(query2folder)):
    count = 0
    if(filename != '.DS_Store' and (filename.split('.')[1] == 'jpg')):
        print("******************************************************************************")
        print("./qsd2_w1/" + filename)
        print("******************************************************************************")

        query_img = cv2.imread(query2folder + filename)
        
        gray = cv2.cvtColor(query_img, cv2.COLOR_BGR2GRAY)

        ret, thresh = cv2.threshold(gray,0,255,cv2.THRESH_BINARY_INV+cv2.THRESH_OTSU)

        # noise removal
        kernel = np.ones((3,3),np.uint8)
        opening = cv2.morphologyEx(thresh,cv2.MORPH_OPEN,kernel, iterations = 2)

        # sure background area
        sure_bg = cv2.dilate(opening,kernel,iterations=3) #Fals. El sure 


        # Finding sure foreground area
        dist_transform = cv2.distanceTransform(opening,cv2.DIST_L2,3)
        ret, sure_fg = cv2.threshold(dist_transform,0.15*dist_transform.max(),255,0) #0.15 26.57% 



        # Finding unknown region
        sure_fg = np.uint8(sure_fg)
        unknown = cv2.subtract(sure_bg,sure_fg)

        # Marker labelling
        ret, markers = cv2.connectedComponents(sure_fg)

        markers[markers != 0] = 200
        
        #35
        markers[0:40,:] = 100
        sure_fg[0:40,:] = 100
        markers[len(markers)-41:len(markers)-1,:] = 100
        sure_fg[len(markers)-41:len(markers)-1,:] = 100
        markers[:,0:40] = 100
        sure_fg[:,0:40] = 100
        markers[:,len(markers[0,:])-41:len(markers[0,:])-1] = 100
        sure_fg[:,len(markers[0,:])-41:len(markers[0,:])-1] = 100

        # Add one to all labels so that sure background is not 0, but 1
        markers = markers+1

        # Now, mark the region of unknown with zero
        markers[sure_fg == 0] = 0

        markersres = cv2.watershed(query_img,markers)

        markersres[markersres == 201] = 255
        markersres[markersres == 101] = 0
        markersres[markersres == -1] = 255
        
        #Make the mask binary
        markersres = markersres/np.max(markersres)
        
        #Apply the mask to the image
        color = ('b','g','r')
        
        #Compute the histogram
        query_img = cv2.cvtColor(query_img,cv2.COLOR_BGR2Lab)
        
        print(markersres.dtype)
        mask = markersres.astype('uint8') 
        
        hist_query = np.empty([0, 256*3])
        for i,col in enumerate(color):
            histr = cv2.calcHist([query_img],[i],mask,[256],[0,256])
            print(histr.shape)
            #histr = histr/max(histr)
            histr = histr.transpose()
            if i == 0:
                hist_query = histr
            else:
                hist_query = np.concatenate((hist_query,histr), axis = 1)
        
        cv2.normalize(hist_query, hist_query, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX)
        
        #Save to the histogram_query matrix      
        histogram_query2_matrix = np.vstack((histogram_query2_matrix, hist_query))
        
        


******************************************************************************
./qsd2_w1/00000.jpg
******************************************************************************
float64
(256, 1)
(256, 1)
(256, 1)
******************************************************************************
./qsd2_w1/00001.jpg
******************************************************************************
float64
(256, 1)
(256, 1)
(256, 1)
******************************************************************************
./qsd2_w1/00002.jpg
******************************************************************************
float64
(256, 1)
(256, 1)
(256, 1)
******************************************************************************
./qsd2_w1/00003.jpg
******************************************************************************
float64
(256, 1)
(256, 1)
(256, 1)
******************************************************************************
./qsd2_w1/00004.jpg
*************************************************

In [5]:
from scipy.spatial import distance

dst = np.zeros((30, 279))
matrix_retrieval = np.zeros((30,10))

for query_image_index in range(0,len(histogram_query2_matrix)): 
    for bbdd_image_index in range(0, len(histogram_bbdd_matrix)):
        
        #Euclidian distance 1
        dst[query_image_index,bbdd_image_index] = distance.euclidean(histogram_query2_matrix[query_image_index,:], histogram_bbdd_matrix[bbdd_image_index,:])
        
        #Euclidian distance 2
        dst[query_image_index,bbdd_image_index] = np.linalg.norm(histogram_query2_matrix[query_image_index,:] - histogram_bbdd_matrix[bbdd_image_index,:], ord=1)
        
        #Bray Curtis Distance
        dst[query_image_index,bbdd_image_index] = distance.braycurtis(histogram_query2_matrix[query_image_index,:], histogram_bbdd_matrix[bbdd_image_index,:])
    
    matrix_retrieval[query_image_index,:] = np.argsort(dst[query_image_index,:])[:10]

print(matrix_retrieval)

[[263. 115.  72. 112. 182. 258.  10. 185.   1.  61.]
 [ 36. 221.  62.  80. 257. 239.  41.  61. 217. 182.]
 [ 43. 154. 150.  13. 233. 174.  75. 196.  58. 272.]
 [129. 217.  41. 239.  42.  36. 211.  78. 221. 257.]
 [ 42. 182. 221. 258.  61. 266. 112. 257. 268.  72.]
 [  0. 218. 236.  56. 247. 150.  71. 272. 240.  13.]
 [ 33.  18.  40. 155. 238.   8. 198. 193. 112.  34.]
 [ 97. 276.  44.  59.  38. 275.  92.  76.  56.  70.]
 [ 41.  62.  36.  72. 239. 102. 258. 257.  88. 221.]
 [180. 123. 198.  33. 260.  34. 225. 228. 106.  69.]
 [ 73.  58.  69. 198. 117. 203. 264.  92. 272.  79.]
 [127. 255.   1. 191. 185. 213. 263. 178. 209. 115.]
 [155. 193. 143. 102.  10. 258. 112. 115.  88. 238.]
 [ 92. 225. 106.  34.  75.  97. 180. 203.  59. 206.]
 [ 70. 147. 105. 155. 238. 195.  18. 193. 137.  33.]
 [131. 238. 195. 210. 105.  70.  29. 220. 203. 272.]
 [215. 219. 277. 127. 137. 192. 111. 136. 190. 209.]
 [147.  62. 115.  72.   1.  10. 102.  61. 141. 257.]
 [180. 198. 123. 260.  33.  34. 225.  18. 203.

In [6]:
import ml_metrics as metrics
import pickle

with open('./qsd2_w1/gt_corresps.pkl', 'rb') as fd:
        ll = pickle.load(fd)
        print(ll)

#Convertir idx(numpy) a list of lists
matrix_retrieval_lst = matrix_retrieval.tolist()

#print(matrix_retrieval_lst)

ll_prp = np.zeros((len(ll),1))

for i in range(0,len(ll)):
    ll_prp[i] = ll[i][0]

ll_prp_lst = ll_prp.tolist()

mapak = metrics.average_precision.mapk(ll_prp_lst, matrix_retrieval_lst, k=10)        

print(mapak)

[[228], [62], [0], [129], [42], [218], [40], [101], [279], [180], [73], [127], [155], [106], [193], [131], [215], [257], [155], [139], [171], [5], [205], [14], [160], [249], [147], [66], [242], [6]]
0.4658333333333333


# PROVES POL

In [8]:
with open('result.pkl', 'rb') as fd:
    ll = pickle.load(fd)
    print(ll)

[[131.0, 244.0, 237.0, 30.0, 238.0, 179.0, 245.0, 210.0, 147.0, 107.0], [6.0, 212.0, 262.0, 149.0, 116.0, 134.0, 104.0, 210.0, 50.0, 163.0], [122.0, 124.0, 151.0, 191.0, 255.0, 185.0, 127.0, 29.0, 244.0, 245.0], [180.0, 123.0, 260.0, 198.0, 33.0, 34.0, 225.0, 106.0, 228.0, 69.0], [147.0, 238.0, 115.0, 8.0, 72.0, 141.0, 10.0, 102.0, 61.0, 112.0], [271.0, 263.0, 191.0, 88.0, 182.0, 143.0, 11.0, 185.0, 57.0, 257.0], [92.0, 225.0, 106.0, 34.0, 97.0, 75.0, 180.0, 203.0, 59.0, 206.0], [147.0, 70.0, 105.0, 155.0, 238.0, 195.0, 18.0, 137.0, 193.0, 33.0], [73.0, 58.0, 198.0, 69.0, 117.0, 203.0, 264.0, 272.0, 92.0, 75.0], [59.0, 97.0, 92.0, 38.0, 225.0, 275.0, 139.0, 76.0, 200.0, 260.0], [30.0, 191.0, 255.0, 185.0, 271.0, 127.0, 107.0, 3.0, 209.0, 143.0], [205.0, 235.0, 111.0, 96.0, 52.0, 72.0, 193.0, 190.0, 143.0, 137.0], [70.0, 59.0, 100.0, 38.0, 52.0, 14.0, 241.0, 18.0, 220.0, 145.0], [73.0, 92.0, 76.0, 58.0, 138.0, 79.0, 31.0, 180.0, 75.0, 82.0], [192.0, 66.0, 134.0, 151.0, 249.0, 232.0, 60.