# TASK 1 - Compute image descriptors (QS1)

In [87]:
import cv2
import numpy as np
np.set_printoptions(threshold=np.inf)
from matplotlib import pyplot as plt
from os.path import isfile, join
from os import listdir
from sklearn import preprocessing

### Calcular els histogrames de totes les imatges de la carpeta especificada a "imagesFolder"
Aquí la idea es fer el bucle que recorre totes les imatges i calcula el histograma de cadascuna d'elles, afegint el resultat a una matriu d'histogrames que després ens servirán per calcular les "Similarity measures".
Cada fila correspondrà a una imatge. 

In [88]:
imagesFolder = "./bbdd/"
histogram_matrix = np.empty([0, 256*3]) #Creem una matriu buida
print(histogram_matrix.shape)
for filename in sorted(listdir(imagesFolder)):
    if(filename != '.DS_Store' ):
        print("******************************************************************************")
        print("IMAGE: " + filename)
        print("******************************************************************************")

        img = cv2.imread(imagesFolder + filename)
        img = cv2.cvtColor(img,cv2.COLOR_BGR2Lab)
        color = ('x','y','z')
        hist_img = np.empty([0,0])
        for i,col in enumerate(color):
            hist = cv2.calcHist([img],[i],None,[256],[0,256])
            hist = preprocessing.normalize(hist, norm='l2')
            hist_t = hist.transpose()
            print(hist_t.shape)
            if i == 0:
                hist_img = hist_t
            else:
                hist_img = np.concatenate((hist_img, hist_t), axis = 1)
            
        histogram_matrix = np.vstack((histogram_matrix, hist_img))   

(0, 768)
******************************************************************************
IMAGE: bbdd_00000.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00001.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00002.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00003.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00004.jpg
**************************************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00041.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00042.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00043.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00044.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00045.jpg
********************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00088.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00089.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00090.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00091.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00092.jpg
********************************************

******************************************************************************
IMAGE: bbdd_00131.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00132.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00133.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00134.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00135.jpg
***********************************************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00171.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00172.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00173.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00174.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00175.jpg
********************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00213.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00214.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00215.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00216.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00217.jpg
********************************************

(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00253.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00254.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00255.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00256.jpg
******************************************************************************
(1, 256)
(1, 256)
(1, 256)
******************************************************************************
IMAGE: bbdd_00257.jpg
********************************************

In [49]:
print(histogram_matrix.shape)

(279, 768)


### Calcular el histograma de la imatge amb la qual es fa la consulta

In [89]:
queryFolder = "./qsd1_w1/"
histogram_query_matrix = np.empty([0, 256*3])
for filename in sorted(listdir(queryFolder)):
    if(filename != '.DS_Store' and (filename.split('.')[1] == 'jpg' or filename.split('.')[1] == 'png')):
        print("******************************************************************************")
        print("./qsd1_w1/" + filename)
        print("******************************************************************************")

        query_img = cv2.imread(queryFolder + filename)
        query_img = cv2.cvtColor(query_img,cv2.COLOR_BGR2Lab)
        color = ('b','g','r')
        hist_query = np.empty([0, 256*3])
        
        for i,col in enumerate(color):
            histr = cv2.calcHist([query_img],[i],None,[256],[0,256])
            histr = preprocessing.normalize(histr, norm='l2')
            histr = histr.transpose()
            if i == 0:
                hist_query = histr
            else:
                hist_query = np.concatenate((hist_query,histr), axis = 1)
        
        histogram_query_matrix = np.vstack((histogram_query_matrix, hist_query))
    


******************************************************************************
./qsd1_w1/00000.jpg
******************************************************************************
******************************************************************************
./qsd1_w1/00001.jpg
******************************************************************************
******************************************************************************
./qsd1_w1/00002.jpg
******************************************************************************
******************************************************************************
./qsd1_w1/00003.jpg
******************************************************************************
******************************************************************************
./qsd1_w1/00004.jpg
******************************************************************************
******************************************************************************
./qsd1_w1/00005.jpg
***********

# TASK 2 - Similarity measures

### Euclidean distance

In [99]:
from scipy.spatial import distance

dst = np.zeros((30, 279))
idx = np.zeros((30,10))

for query_image_index in range(0,len(histogram_query_matrix)): 
    for i in range(0, len(histogram_matrix)):
        #dst[query_image_index,i] = distance.euclidean(histogram_query_matrix[query_image_index,:], histogram_matrix[i,:])
        dst[query_image_index,i] = np.linalg.norm(histogram_query_matrix[query_image_index,:] - histogram_matrix[i,:], ord=1)
        
    
    idx[query_image_index,:] = np.argsort(dst[query_image_index,:])[:10]

print(idx)

[[154. 131.  91. 140. 173. 162.  81.  19.   7. 167.]
 [125. 116. 133. 157. 140. 207. 177. 261. 162. 154.]
 [207. 274. 165. 172. 187.  81.  89. 237. 157. 133.]
 [ 70.  31.  60. 180.   4. 128. 172. 157.  89. 232.]
 [147. 184. 161.  56. 265.  87. 136. 171. 270.  46.]
 [ 83. 271. 246. 142.  90. 136. 225. 180.  65. 262.]
 [198. 180. 245.  60.  84. 204. 255. 149. 117. 172.]
 [181.  95. 238. 198.  18. 253.  33. 252. 245. 204.]
 [ 73. 144. 138. 148. 123. 268.  20. 215.  59.  82.]
 [ 12. 137. 228.  59.  82.  32.   3.  58.  44.  25.]
 [244. 205.  80. 264.  83.  63.  70. 232. 101.  92.]
 [177.  70. 205. 157. 232. 176. 116. 207. 179.  30.]
 [133.  19. 125. 179. 232. 176. 205. 177. 131.  81.]
 [ 73. 144.  46. 138. 148. 123. 215. 147. 268. 184.]
 [223. 186.  13. 267. 242. 213. 114.  43. 152.   2.]
 [189.  98.  47.  48.  37. 212. 247. 103. 119. 269.]
 [150. 187.  49. 208.  75. 161. 188. 274.  89. 240.]
 [194.  31. 180. 128.  18.  30.  70.  60. 117. 198.]
 [  4. 158. 187.  70. 176. 188.  60. 232. 157.

In [100]:
import ml_metrics as metrics
import pickle

with open('./qsd1_w1/gt_corresps.pkl', 'rb') as fd:
        ll = pickle.load(fd)

gt = np.empty((0,0))

#Convertir idx a list of lists
idx_lst = idx.tolist()

ll_prp = np.zeros((len(ll),1))

for i in range(0,len(ll)):
    ll_prp[i] = ll[i][0][1]

ll_prp_lst = ll_prp.tolist()

mapak = metrics.average_precision.mapk(ll_prp_lst, idx_lst, k=10)        

print(mapak)

0.41777777777777775
